prediction_pipeline:
  estimator_name: "random_forest_regressor"
  regressor_dict:
    n_estimators: 400
    criterion: "squared_error"
    max_depth: 14
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 1.0
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: True
    oob_score: False
    n_jobs: null
    random_state: 42
    verbose: 0
    warm_start: False
    ccp_alpha: 0.0
    max_samples: null
    monotonic_cst: null